var JSQuizQuestions = ["Inside which HTML element do we put the JavaScript?","What is the correct syntax for referring to an external script called 'ABC.js'?","How do you write 'I love pancakes' in an alert box?","How do you create a function in JavaScript?","How do you call a function named 'pizzaPants'?","How do you write an IF statement for executing some code if 'i' is NOT equal to 282?","How do you comment out code in JavaScript?","How do you declare a variable in JavaScript?","Which operator is used to assign a value to a variable?","How do you generate a random number in JavaScript?"];
var JSQuizAnswerA = ["<scripting>","<script src ='ABC.js'>","alertBox('I love pancakes');","function myFunction()","pizzaPants()","if (i < 282)","<!-- -->","v pizzaRolls;","*","randomNum();"];
var JSQuizAnswerB = ["<script>","<script href ='ABC.js'>","ALERT!('I love pancakes');","function.myFunction{}","call pizzaPants()","if (i <> 282)","'' ''","var pizzaRolls;","-","randomMath();"];
var JSQuizAnswerC = ["<javascript>","<script url ='ABC.js'>","alert('I love pancakes');","function = myFunction()","function.pizzaPants()","if (i <= 282)","//","variable set pizzaRolls;","=","MathRandom();"];
var JSQuizAnswerD = ["<pizza>","<script name ='ABC.js'>","msg('I love pancakes');","var function:myFunction()","pizzaPants{()}","if (i != 282)","<comment!-- -->","pizzaRolls;","/","Math.random();"];

var JSQuizAnswerKey = ["B","A","C","A","A","D","C","B","C","D"];

var CSSQuizQuestions = ["What does CSS stand for?","What is the correct HTML for referring to an external style sheet?","Which HTML attirbute is used to define inline styles?","What is correct CSS syntax?","How do you comment code in a CSS file?","Which property changes background color?","What property controls text size?","Which CSS property changes the font of an element?","How do you adjust the right margin of an element?","How do you select an element with an id of 'pizzaTop'?"];
var CSSQuizAnswerA = ["cascading style sheet","<linkstyle = style.css>","value","body:color=black;","''","background-color","text-size","font-font","margin-right","pizzaTop"];
var CSSQuizAnswerB = ["background color","<style src='style.css'>","class","body {color: black;}","/*  */","bkgColor","text-style","font-src","padding-right","#pizzaTop"];
var CSSQuizAnswerC = ["collapse system strudel","<stylesheet>style.css</stylesheet>","style","{body:color=black;}","// //","color","font-style","font-family","margin-top",".pizzaTop"];
var CSSQuizAnswerD = ["cascading sorting sheet","<link rel='stylesheet' type='text/css' href='style.css'>","styles","{body;color:black;}","//","b-groundcolor","font-size","fonr-weight","maple syrup","id-pizzaTop"];

var CSSQuizAnswerKey = ["A","D","C","B","B","A","D","C","A","B"];

var DTQuizQuestions = ["How many doughnuts are made in the U.S. each year?","How many people, in America, have the last name of 'doughnut' or 'donut'?","What author waxed poetic about doughnuts?","The earliest origins to the modern doughnuts are generally traced back to the Dutch settlers in early New York. What other name did the doughnuts go by?","The word 'nut' in doughnut was used in it's earlier sense. What did 'nut' refer to?","In what year was the first known printed use of the word 'donut'?","The french had a variant their version of the doughnut, which was called 'pets de nonne', which translates to what?","The doughnut shop 'VooDoo Doughnut' was famous for it's absurd flavors. What was on one of it's 'medicinal' donuts?","A 19th-century New England ship captain claims to have invented the hole in doughnuts. Who was he?","According to anthropologist Paul R. Mullins, the first cookbook mentioning doughnuts was in what year?"];
var DTQuizAnswerA = ["200,000","20","Mark Twain","Dow nuts","small round cake or cookie","1900","No pets","cheap weed and applesauce","Black Beard","1779"];
var DTQuizAnswerB = ["4,000,000","10","Franz Kafka","ring cakes","hot oil","1929","crow's feet","NyQuil and Pepto Bismol","Jack Sparrow","1850"];
var DTQuizAnswerC = ["25","6,000","Washington Irving","crullers","flour made from nuts","1808","Nun's farts","vicodin and cocaine","Ernest Krause","1915"];
var DTQuizAnswerD = ["10,000,000,00","451","Ernest Hemingway","olykeok","a nut for a bolt","2205","air dough","cheese and chocolate","Hanson Gregory","1803"];

var DTQuizAnswerKey = ["D","B","C","D","A","A","C","B","D","D"];